/**
 * The ISO 3166-1 alpha-2 code for each country in COUNTRIES
 * (src/config/countries.ts), keyed by its display name. Used to show the
 * country's flag in the countries picker. A test checks every country has
 * exactly one valid code, so a country added there without one fails CI.
 */
export const COUNTRY_CODES = {
  Afghanistan: "AF",
  Algeria: "DZ",
  Argentina: "AR",
  Australia: "AU",
  Austria: "AT",
  Bangladesh: "BD",
  Botswana: "BW",
  Brazil: "BR",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  China: "CN",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  "Dominican Republic": "DO",
  "DR Congo": "CD",
  Egypt: "EG",
  Ethiopia: "ET",
  Finland: "FI",
  France: "FR",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guatemala: "GT",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Latvia: "LV",
  Lebanon: "LB",
  Libya: "LY",
  Malaysia: "MY",
  Mali: "ML",
  Malta: "MT",
  Mexico: "MX",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nepal: "NP",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Nigeria: "NG",
  "North Korea": "KP",
  Norway: "NO",
  Pakistan: "PK",
  Palestine: "PS",
  Panama: "PA",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  Senegal: "SN",
  Serbia: "RS",
  Singapore: "SG",
  Slovakia: "SK",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  Sudan: "SD",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  Tanzania: "TZ",
  Thailand: "TH",
  "The Gambia": "GM",
  Tunisia: "TN",
  Turkey: "TR",
  Uganda: "UG",
  Ukraine: "UA",
  "United Kingdom": "GB",
  "United States": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
} as const satisfies Record<string, string>;

export type CountryCode = (typeof COUNTRY_CODES)[keyof typeof COUNTRY_CODES];

/** The code for a country name, or null for a name outside the map. */
export function countryCode(country: string): CountryCode | null {
  return Object.hasOwn(COUNTRY_CODES, country) ? COUNTRY_CODES[country as keyof typeof COUNTRY_CODES] : null;
}
