// Single runtime source of truth for the curated topic/source lists — the
// onboarding multi-select, its zod validation, and FEEDS all read from
// these arrays instead of the type system silently drifting from what's
// actually selectable.
export const TOPICS = [
  "Tech/AI",
  "Cybersecurity",
  "Consumer Tech & Gadgets",
  "Gaming",
  "Space",
  "Science",
  "Climate & Environment",
  "Energy Transition & Renewables",
  "Health & Medicine",
  "Biotech & Pharma",
  "US Politics",
  "Morocco Politics",
  "French Politics",
  // A container: each country a reader picks inside it is its own reading
  // unit (src/lib/readingUnits.ts). Placed before the regional topics so an
  // article shared with one of them is tagged with the reader's country.
  "Countries",
  "Geopolitics",
  "Morocco",
  "UK Politics",
  "European Union",
  "Middle East",
  "Africa",
  "Asia-Pacific",
  "Latin America",
  "Elections",
  "Immigration",
  "Defense & Security",
  "Human Rights",
  "Morocco Finance",
  "US Finance",
  "World Finance",
  "Economy",
  "Markets & Investing",
  "Personal Finance",
  "Real Estate",
  "Energy & Oil",
  "Crypto",
  "Banking",
  "Retail & Consumer",
  "Automotive",
  "Football",
  "Basketball",
  "Tennis",
  "American Football",
  "Formula 1",
  "Cricket",
  "Rugby",
  "Golf",
  "Boxing & MMA",
  "Cycling",
  "Baseball",
  "Olympics & Athletics",
  "Film & TV",
  "Music",
  "Books",
  "Art & Design",
  "Architecture",
  "Food & Drink",
  "Travel",
  "Fashion",
  "Celebrity & Entertainment",
  "Education",
  "Religion",
  "Health & Wellness",
  "Law & Courts",
  "Crime",
  "Weather & Natural Disasters",
  "Media & Journalism",
] as const;
export type Topic = (typeof TOPICS)[number];

export const SOURCES = [
  "NYT",
  "BBC",
  "TechCrunch",
  "The Verge",
  "Ars Technica",
  "Engadget",
  "Wired",
  "The Hill",
  "Politico",
  "Hespress (EN)",
  "Hespress (FR)",
  "Le Monde",
  "Le Figaro",
  "France24",
  "RFI (EN)",
  "RFI (FR)",
  "The Guardian",
  "Al Jazeera",
  "DW",
  "The North Africa Post",
  "Challenge.ma",
  "CNBC",
  "MarketWatch",
  "Bloomberg",
  "Financial Times",
  "The Economist",
  "ESPN",
  "Football Italia",
  "Marca",
  "RMC Sport",
  "Kicker",
  "Transfermarkt",
  "The Athletic",
  "Yahoo Sports",
  "CBS Sports",
  "RotoWire",
  "Hoops Rumors",
  "Tennis365",
  "Tennis Majors",
  "UbiTennis",
  "Pro Football Talk",
  "IEEE Spectrum",
  "MIT Technology Review",
  "BleepingComputer",
  "The Record",
  "Dark Reading",
  "9to5Mac",
  "Tom's Hardware",
  "Android Authority",
  "IGN",
  "Kotaku",
  "PC Gamer",
  "SpaceNews",
  "Phys.org",
  "ScienceDaily",
  "NPR",
  "Scientific American",
  "Science (AAAS)",
  "Inside Climate News",
  "Grist",
  "Carbon Brief",
  "CleanTechnica",
  "Canary Media",
  "Electrek",
  "InsideEVs",
  "CBS News",
  "STAT News",
  "Endpoints News",
  "PBS NewsHour",
  "NBC News",
  "LA Times",
  "ABC News",
  "TelQuel",
  "BFM TV",
  "Euronews",
  "Sky News",
  "The Diplomat",
  "Foreign Policy",
  "Yabiladi",
  "Politico Europe",
  "Mail & Guardian",
  "Premium Times (Nigeria)",
  "AllAfrica",
  "Daily Maverick",
  "The East African",
  "Nation (Kenya)",
  "Le Monde Afrique",
  "South China Morning Post",
  "Times of India",
  "The Hindu",
  "Channel NewsAsia",
  "Japan Times",
  "MercoPress",
  "Buenos Aires Times",
  "InfoMigrants",
  "War on the Rocks",
  "The War Zone",
  "Breaking Defense",
  "Defense News",
  "Human Rights Watch",
  "Amnesty International",
  "Fortune",
  "Forbes",
  "HousingWire",
  "OilPrice.com",
  "Rigzone",
  "Cointelegraph",
  "CoinDesk",
  "The Block",
  "Banking Dive",
  "Retail Dive",
  "WWD",
  "Autocar",
  "Motor1",
  "Car and Driver",
  "Hesport",
  "L'Équipe",
  "Motorsport.com",
  "Autosport",
  "The Race",
  "ESPNcricinfo",
  "RugbyPass",
  "MMA Fighting",
  "Cyclingnews",
  "MLB Trade Rumors",
  "Deadline",
  "Variety",
  "IndieWire",
  "The Hollywood Reporter",
  "NME",
  "Rolling Stone",
  "Pitchfork",
  "Billboard",
  "Literary Hub",
  "Dezeen",
  "Designboom",
  "The Art Newspaper",
  "ARTnews",
  "ArchDaily",
  "Eater",
  "Skift",
  "Condé Nast Traveler",
  "Vogue",
  "Inside Higher Ed",
  "Religion News Service",
  "Lawfare",
  "The Marshall Project",
  "Nieman Lab",
  "Poynter",
  "Press Gazette",
  // Country outlets: each appears only in COUNTRY_FEEDS (src/config/countries.ts).
  "Amu TV",
  "KabulNow",
  "Khaama Press",
  "Hasht-e Subh",
  "TSA",
  "Algérie360",
  "Echorouk",
  "Buenos Aires Herald",
  "Clarín",
  "La Nación",
  "ABC (Australia)",
  "Crikey",
  "The Local Austria",
  "Der Standard",
  "Die Presse",
  "Kurier",
  "The Business Standard",
  "Dhaka Tribune",
  "Sunday Standard",
  "The Botswana Gazette",
  "Weekend Post",
  "Agência Brasil",
  "The Rio Times",
  "Folha de S.Paulo",
  "G1",
  "Novinite",
  "BTA",
  "Dnevnik",
  "Mediapool",
  "Lefaso.net",
  "Burkina24",
  "Sidwaya",
  "Khmer Times",
  "CamboJA News",
  "Phnom Penh Post",
  "Actu Cameroun",
  "Cameroon News Agency",
  "Mimi Mefo Info",
  "Data Cameroon",
  "Global News",
  "National Post",
  "The Globe and Mail",
  "Radio-Canada",
  "La Tercera",
  "Cooperativa",
  "China Digital Times",
  "The Tico Times",
  "La Nación (Costa Rica)",
  "Delfino",
  "Linfodrome",
  "Ivoirematin",
  "Connectionivoirienne",
  "Croatia Week",
  "Total Croatia News",
  "Index.hr",
  "14ymedio",
  "Havana Times",
  "Diario de Cuba",
  "Cyprus Mail",
  "In-Cyprus",
  "Politis",
  "Financial Mirror",
  "Expats.cz",
  "ČT24",
  "Novinky.cz",
  "iRozhlas",
  "Radio Prague International",
  "The Local Denmark",
  "The Copenhagen Post",
  "Politiken",
  "Dominican Today",
  "El Nuevo Diario (DR)",
  "N Digital",
  "Actualite.cd",
  "Politico.cd",
  "Zoom Eco",
  "Congo Indépendant",
  "Egypt Independent",
  "Daily News Egypt",
  "Mada Masr",
  "Egyptian Streets",
  "Fana",
  "Ethiopia Observer",
  "Ethiopia Insight",
  "Capital Ethiopia",
  "Helsinki Times",
  "Helsingin Sanomat",
  "Yle",
  "The Local France",
  "The Local Germany",
  "Tagesschau",
  "MyJoyOnline",
  "Graphic Online",
  "3News",
  "To Vima",
  "Kathimerini",
  "Greek City Times",
  "Prensa Libre",
  "República (Guatemala)",
  "Plaza Pública",
  "Agencia Ocote",
  "ConCriterio",
  "Hong Kong Free Press",
  "RTHK",
  "The Witness",
  "Hungary Today",
  "Daily News Hungary",
  "Hungarian Conservative",
  "444.hu",
  "HVG",
  "Index.hu",
  "Budapest Times",
  "RÚV English",
  "Iceland Review",
  "Iceland Monitor",
  "Grapevine",
  "NDTV",
  "Hindustan Times",
  "Scroll",
  "Antara",
  "CNN Indonesia",
  "Republika",
  "IranWire",
  "Amwaj.media",
  "Iraqi News",
  "Kurdistan24",
  "RTÉ",
  "The Irish Times",
  "Irish Examiner",
  "The Jerusalem Post",
  "Haaretz",
  "JNS",
  "Israel Hayom",
  "ANSA",
  "The Local Italy",
  "la Repubblica",
  "Decode39",
  "Japan Today",
  "The Mainichi",
  "Nippon.com",
  "Roya News",
  "Jordan News",
  "7iber",
  "The Astana Times",
  "Tengrinews",
  "Kursiv",
  "The Standard (Kenya)",
  "Capital FM (Kenya)",
  "Kenyans.co.ke",
  "KBC",
  "Tuko",
  "LSM",
  "LSM (Latvian)",
  "Delfi (Latvia)",
  "TVNET",
  "Baltic News Network",
  "The961",
  "Beirut Today",
  "NOW Lebanon",
  "Annahar",
  "Libya Herald",
  "Libya Review",
  "Libya Update",
  "Malay Mail",
  "Free Malaysia Today",
  "Malaysiakini",
  "Studio Tamani",
  "Mali Actu",
  "Newsbook",
  "Lovin Malta",
  "The Shift",
  "Mexico News Daily",
  "La Jornada",
  "El Financiero",
  "Le Desk",
  "Club of Mozambique",
  "Zitamar",
  "O País (Mozambique)",
  "The Irrawaddy",
  "Myanmar Now",
  "DVB",
  "The Namibian",
  "New Era",
  "Windhoek Observer",
  "The Himalayan Times",
  "Onlinekhabar English",
  "RNZ",
  "The Spinoff",
  "1News",
  "Confidencial",
  "Divergentes",
  "Artículo 66",
  "Despacho 505",
  "Punch",
  "Vanguard",
  "Channels TV",
  "Daily Trust",
  "BusinessDay (Nigeria)",
  "ThisDay",
  "NK News",
  "Daily NK",
  "38 North",
  "The Local Norway",
  "NRK",
  "VG",
  "Aftenposten",
  "Dawn",
  "The Express Tribune",
  "Geo News",
  "Business Recorder",
  "Mondoweiss",
  "+972 Magazine",
  "La Prensa (Panama)",
  "TVN Panamá",
  "Newsroom Panama",
  "Critica",
  "El Comercio (Peru)",
  "La República (Peru)",
  "Andina",
  "RPP",
  "Inquirer",
  "Rappler",
  "Philstar",
  "GMA News",
  "Notes from Poland",
  "Rzeczpospolita",
  "Gazeta Wyborcza",
  "Onet",
  "TVN24",
  "The Portugal News",
  "Portugal Resident",
  "Público",
  "El Nuevo Día",
  "Centro de Periodismo Investigativo",
  "Primera Hora",
  "Digi24",
  "HotNews.ro",
  "G4Media",
  "The Moscow Times",
  "Meduza",
  "Novaya Gazeta Europe",
  "KT Press",
  "Taarifa",
  "The Chronicles",
  "Seneweb",
  "APS (Senegal)",
  "Senego",
  "RTS (Serbia)",
  "Danas",
  "N1",
  "Nova.rs",
  "Insajder",
  "The Straits Times",
  "The Business Times",
  "The Independent (Singapore)",
  "Aktuality.sk",
  "Denník N",
  "Pravda (Slovakia)",
  "The Citizen (South Africa)",
  "Moneyweb",
  "GroundUp",
  "IOL",
  "Yonhap",
  "The Korea Herald",
  "The Local Spain",
  "The Olive Press",
  "El País",
  "El Mundo",
  "Radio Dabanga",
  "Sudans Post",
  "Darfur24",
  "The Local Sweden",
  "SVT",
  "Aftonbladet",
  "Expressen",
  "The Local Switzerland",
  "SRF",
  "Le Temps",
  "NZZ",
  "RTS",
  "Tages-Anzeiger",
  "Enab Baladi",
  "Syrian Observer",
  "Syria Direct",
  "North Press Agency",
  "Levant24",
  "Daily News (Tanzania)",
  "The Chanzo",
  "Bangkok Post",
  "Khaosod English",
  "Thai Enquirer",
  "The Standard (Gambia)",
  "Kerr Fatou",
  "The Alkamba Times",
  "Kapitalis",
  "La Presse (Tunisia)",
  "Webdo",
  "Leaders",
  "Daily Sabah",
  "Turkish Minute",
  "Bianet",
  "Hürriyet Daily News",
  "Medyascope",
  "Anadolu Agency",
  "The Independent (Uganda)",
  "PML Daily",
  "The Observer (Uganda)",
  "SoftPower",
  "Ukrainska Pravda",
  "Kyiv Post",
  "Ukrinform",
  "Euromaidan Press",
  "Evening Standard",
  "Daily Mirror",
  "Channel 4 News",
  "Montevideo Portal",
  "la diaria",
  "Gazeta.uz",
  "UzDaily",
  "Daryo",
  "Spot.uz",
  "Caracas Chronicles",
  "Efecto Cocuyo",
  "El Pitazo",
  "Lusaka Times",
  "Diggers",
  "Zambia Monitor",
  "NewZimbabwe",
  "Nehanda Radio",
  "The Zimbabwe Independent",
  "ZimEye",
] as const;
export type Source = (typeof SOURCES)[number];

export interface Article {
  title: string;
  snippet: string;
  url: string;
  source: Source;
  topic: Topic;
  /** The country within Countries this article was read for; null or absent otherwise. */
  subtopic?: string | null;
  publishedAt: string;
}

export interface Cluster {
  topic: Topic;
  /** Taken from the same article as `topic`. */
  subtopic?: string | null;
  articles: Article[];
}

export interface Card {
  id: string;
  topic: Topic;
  /** Short headline (5-8 words), written by writeCard.ts alongside shortSummary. Empty string for pre-5.5 rows (no migration backfill). */
  title: string;
  shortSummary: string;
  /** 1-2 free-form, LLM-generated tags — a more specific angle on the story than topic alone. Empty array for pre-5.5 rows. */
  labels: string[];
  /**
   * Null until the first time a user expands the card; generated once by
   * generateExpandedReport() and cached on the row from then on. Includes
   * snippet (not just title/url/source) so a lazy report written days
   * after the original cluster is gone from memory still has real source
   * text to work from, without re-fetching source URLs.
   */
  expandedReport: string | null;
  /**
   * `sig` is the server's signature over `url` (see sourceLinks.ts). The full
   * report fetches only links whose signature verifies, since a signed-in user
   * can store any `sources` through persist_generated_cards.
   */
  sources: (Pick<Article, "title" | "url" | "source" | "snippet"> & { sig?: string })[];
  /** Most recent publishedAt across the cluster's source articles. */
  publishedAt: string;
  /**
   * When this card's generation run persisted it — distinct from
   * publishedAt (source-article recency). Every card from the same
   * same-day run shares an identical value (see persist_generated_cards),
   * which is what lets the feed identify the latest run and badge its
   * cards as New (see newRun.ts).
   */
  generatedAt: string;
  bookmarked: boolean;
  /**
   * 1-5, graded by triage relative to this card's own topic's typical-day
   * baseline (same independence philosophy as the old boolean `notable`
   * gate, just more granular). Drives topic-page box sizing.
   */
  severity: number;
  /**
   * 1-6 if this card is one of today's front-page picks, null otherwise.
   * Set by rank.ts's cross-topic ranking pass, which re-runs against the
   * full cumulative pool of today's cards on every digest generation — so
   * this can change (including being cleared back to null) on a later run
   * of the same day, not just assigned once.
   */
  frontPageRank: number | null;
  /** The country within Countries this card covers; null or absent for every other topic. */
  subtopic?: string | null;
}

export interface Digest {
  id: string;
  date: string;
  /** Null if this digest's first generation run hasn't completed successfully yet. */
  lastGeneratedAt: string | null;
  cards: Card[];
}
